version: 2

project_name: total-recall

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/total-recall
    binary: total-recall
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: git
  sort: asc
  abbrev: 7
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Refactoring"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Testing"
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999
  filters:
    exclude:
      - "^Merge "
      - "^chore:"
      - "^style:"
