package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/charmbracelet/huh"
	"github.com/colinwilliams91/total-recall/internal/cache"
	"github.com/colinwilliams91/total-recall/internal/config"
	"github.com/colinwilliams91/total-recall/internal/engine"
	"github.com/colinwilliams91/total-recall/internal/hooks"
	"github.com/colinwilliams91/total-recall/internal/recall"
	"github.com/spf13/cobra"
)

var version = "dev"

// quiet is set by the --quiet/-q persistent flag and suppresses advisory messages.
var quiet bool

func main() {
	root := &cobra.Command{
		Use:     "total-recall",
		Short:   "Total Recall — Preserve engineering cogitation in the age of AI-assisted coding",
		Version: version,
	}

	root.PersistentFlags().BoolVarP(&quiet, "quiet", "q", false,
		"Suppress advisory messages (auto-created config notices, etc.)")

	root.AddCommand(
		serveCmd(),
		initCmd(),
		configCmd(),
		statusCmd(),
		askCmd(),
	)

	if err := root.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func serveCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "serve",
		Short: "Start the Total Recall daemon on localhost:7331",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(quiet)
			if err != nil {
				return fmt.Errorf("loading config: %w", err)
			}

			provider, err := newProvider(cfg.AI)
			if err != nil {
				if isErrNoProvider(err) {
					log.Println("[daemon] AI provider not configured — recall questions will not be generated. Run 'total-recall init' to configure.")
				} else {
					log.Printf("[daemon] AI provider error: %v — running without recall.", err)
				}
				provider = nil
			}

			store, err := cache.Open()
			if err != nil {
				return fmt.Errorf("opening concept cache: %w", err)
			}
			defer store.Close()

			var recallEngine *recall.Engine
			if provider != nil {
				recallEngine = recall.New(provider, store)
			}

			return engine.New(cfg, provider, store, recallEngine).Start()
		},
	}
}

// conversationAnalysisPrompt is the description shown in the init opt-in prompt.
// Simple, earnest language — no legal jargon.
const conversationAnalysisPrompt = `Would you like Total Recall to analyze your AI assistant
conversations to generate smarter, more relevant quiz questions?

When enabled, the model looks at what you and your AI discuss and extracts
only the concepts — nothing else is kept. Raw conversation text
is never stored.

You can change this anytime by editing ~/.tr/config.yaml.`

// postCommitHookScriptTmpl is written to .git/hooks/post-commit by tr init.
// %s is the absolute path of the total-recall binary resolved at init time via
// os.Executable() — avoids relying on `which` or PATH lookup at commit time.
const postCommitHookScriptTmpl = `#!/bin/sh
# total-recall managed
# Surfaces a recall question after each successful commit.
# Generated by 'total-recall init'. Run 'total-recall init' again to reinstall.
if command -v powershell.exe >/dev/null 2>&1; then
    powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& '%s' ask"
    exit $?
fi

exec "%s" ask
`

func buildPostCommitHookScript(selfPath string) string {
	powerShellPath := strings.ReplaceAll(selfPath, "'", "''")
	shellPath := strings.ReplaceAll(selfPath, `"`, `\"`)
	return fmt.Sprintf(postCommitHookScriptTmpl, powerShellPath, shellPath)
}

func initCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "init",
		Short: "Initialize Total Recall for this project and create user config",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runInit()
		},
	}
}

func runInit() error {
	cfgPath, err := config.UserConfigPath()
	if err != nil {
		return err
	}

	// Load existing config so we can preserve any values the user already has.
	// If no config exists yet, start from safe defaults.
	existing, loadErr := config.LoadUserConfig()
	if loadErr != nil {
		existing = nil
	}

	cfg := config.DefaultUserConfig()
	if existing != nil {
		cfg = *existing
	}

	// Prompt the user about conversation analysis opt-in.
	var enableConversationAnalysis bool
	if existing != nil {
		enableConversationAnalysis = existing.Privacy.ConversationAnalysis
	}

	form := huh.NewForm(
		huh.NewGroup(
			huh.NewConfirm().
				Title("🧠  Enable conversation analysis?").
				Description(conversationAnalysisPrompt).
				Value(&enableConversationAnalysis),
		),
	)

	if err := form.Run(); err != nil {
		return fmt.Errorf("prompt: %w", err)
	}

	cfg.Privacy.ConversationAnalysis = enableConversationAnalysis

	// ─── AI Provider Setup ────────────────────────────────────────────────────
	if err := runInitAI(&cfg); err != nil {
		return fmt.Errorf("AI provider setup: %w", err)
	}

	if err := config.WriteUserConfig(&cfg); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}

	fmt.Printf("✓ User config saved to %s\n", cfgPath)
	if enableConversationAnalysis {
		fmt.Println("  Conversation analysis: enabled")
	} else {
		fmt.Println("  Conversation analysis: disabled (enable anytime in ~/.tr/config.yaml)")
	}

	// ─── Hook installation ────────────────────────────────────────────────────
	repoRoot, repoErr := hooks.FindRepoRoot()
	if repoErr != nil {
		fmt.Println("\n  ⚠  Not inside a Git repository — skipping hook installation.")
		fmt.Println("     Run 'total-recall init' from a Git repository root to enable hooks.")
		return nil
	}

	// Load existing repo config to pre-populate selections on re-run.
	existingRepoCfg, _ := config.LoadRepoConfigFromDir(repoRoot)
	var preCommit, commitMsg, prePush bool
	if existingRepoCfg != nil {
		preCommit = existingRepoCfg.Hooks.PreCommit
		commitMsg = existingRepoCfg.Hooks.CommitMsg
		prePush = existingRepoCfg.Hooks.PrePush
	} else {
		// Sensible default: enable pre-commit, leave others off.
		preCommit = true
	}

	fmt.Println()
	hookForm := huh.NewForm(
		huh.NewGroup(
			huh.NewConfirm().
				Title("Enable pre-commit hook?").
				Description("Triggers a recall check on every commit. Highest signal — runs most frequently.").
				Value(&preCommit),
			huh.NewConfirm().
				Title("Enable commit-msg hook?").
				Description("Enriches recall with your commit intent. Runs silently after pre-commit.").
				Value(&commitMsg),
			huh.NewConfirm().
				Title("Enable pre-push hook?").
				Description("Architecture-level recall across all commits in the push. Less frequent.").
				Value(&prePush),
		),
	)

	if err := hookForm.Run(); err != nil {
		return fmt.Errorf("hook prompt: %w", err)
	}

	repoCfg := &config.RepoConfig{}
	if existingRepoCfg != nil {
		*repoCfg = *existingRepoCfg
	}
	repoCfg.Hooks = config.HooksConfig{
		PreCommit: preCommit,
		CommitMsg: commitMsg,
		PrePush:   prePush,
	}

	if err := config.WriteRepoConfig(repoRoot, repoCfg); err != nil {
		return fmt.Errorf("writing .tr.yaml: %w", err)
	}
	fmt.Printf("✓ Repo config saved to %s/.tr.yaml\n", repoRoot)

	installer := hooks.NewInstaller(repoRoot)
	installed, err := installer.InstallEnabled(repoCfg.Hooks)
	if err != nil {
		return fmt.Errorf("installing hooks: %w", err)
	}
	if len(installed) == 0 {
		fmt.Println("  No hooks enabled — skipping hook installation.")
	} else {
		fmt.Printf("✓ Installed %d hook(s) into %s/.git/hooks/\n", len(installed), repoRoot)
		fmt.Println("  Start the daemon with: total-recall serve")
	}

	// ─── Post-commit hook (tr ask) ────────────────────────────────────────────
	fmt.Println()
	fmt.Println("  📬  A post-commit hook will be installed that surfaces a recall question")
	fmt.Println("      in your terminal after each successful commit ('total-recall ask').")
	fmt.Println("      It exits silently in CI/CD environments with no TTY.")

	selfPath, err := os.Executable()
	if err != nil {
		selfPath = "total-recall" // graceful fallback when os.Executable fails
	}
	postCommitScript := buildPostCommitHookScript(selfPath)

	postCommitPath := filepath.Join(repoRoot, ".git", "hooks", "post-commit")
	if err := os.WriteFile(postCommitPath, []byte(postCommitScript), 0o755); err != nil {
		fmt.Printf("  ⚠  Could not install post-commit hook: %v\n", err)
	} else {
		fmt.Println("✓ Installed post-commit hook")
	}

	return nil
}

// providerModelDefaults maps each known provider to a sensible starting model.
var providerModelDefaults = map[string]string{
	"anthropic":  "claude-sonnet-4-5",
	"openai":     "gpt-4o",
	"groq":       "llama-3.1-70b-versatile",
	"ollama":     "llama3.2",
	"lm-studio":  "local-model",
	"qwen":       "qwen3.7-max",
	"minimax":    "MiniMax-M3",
	"deepseek":   "deepseek-v4-pro",
	"openrouter": "deepseek/deepseek-v4-flash:free",
	"custom":     "",
}

// providerAPIKeyPlaceholders maps cloud providers to an env: placeholder shown in the TUI.
var providerAPIKeyPlaceholders = map[string]string{
	"anthropic":  "env:ANTHROPIC_API_KEY",
	"openai":     "env:OPENAI_API_KEY",
	"groq":       "env:GROQ_API_KEY",
	"qwen":       "env:QWEN_API_KEY",
	"minimax":    "env:MINIMAX_API_KEY",
	"deepseek":   "env:DEEPSEEK_API_KEY",
	"openrouter": "env:OPENROUTER_API_KEY",
}

// runInitAI prompts the user to configure an AI provider for recall questions.
// It pre-populates prompts from cfg.AI so re-running init preserves existing choices.
// The caller is responsible for writing the modified cfg to disk.
func runInitAI(cfg *config.UserConfig) error {
	fmt.Println()

	// Pre-fill from existing config; default to anthropic on first run.
	selectedProvider := cfg.AI.Provider
	if selectedProvider == "" {
		selectedProvider = "anthropic"
	}

	providerForm := huh.NewForm(
		huh.NewGroup(
			huh.NewSelect[string]().
				Title("🤖  AI Provider").
				Description("Which AI provider should generate your recall questions?").
				Options(
					huh.NewOption("Anthropic (Claude) — recommended", "anthropic"),
					huh.NewOption("OpenAI (e.g. gpt-4o)", "openai"),
					huh.NewOption("Groq  (cloud · fast · free tier)", "groq"),
					huh.NewOption("Qwen  (e.g. qwen3.7-max)", "qwen"),
					huh.NewOption("MiniMax  (e.g. MiniMax-M3)", "minimax"),
					huh.NewOption("DeepSeek  (e.g. deepseek-v4-pro)", "deepseek"),
					huh.NewOption("OpenRouter  (catalog · deepseek-v4-flash:free)", "openrouter"),
					huh.NewOption("Ollama  (local)", "ollama"),
					huh.NewOption("LM Studio  (local)", "lm-studio"),
					huh.NewOption("Custom  (advanced — any OpenAI-compatible endpoint)", "custom"),
				).
				Value(&selectedProvider),
		),
	)
	if err := providerForm.Run(); err != nil {
		return fmt.Errorf("provider prompt: %w", err)
	}
	cfg.AI.Provider = selectedProvider

	// Pre-populate model from existing config; fall back to provider default.
	model := cfg.AI.Model
	if model == "" {
		model = providerModelDefaults[selectedProvider]
	}
	apiKey := cfg.AI.APIKey
	baseURL := cfg.AI.BaseURL

	switch selectedProvider {
	case "anthropic", "openai", "groq", "qwen", "minimax", "deepseek", "openrouter":
		// Cloud providers: prompt for API key (env: pattern) and model name.
		if apiKey == "" {
			apiKey = providerAPIKeyPlaceholders[selectedProvider]
		}
		followUp := huh.NewForm(
			huh.NewGroup(
				huh.NewInput().
					Title("API Key").
					Description("Use env:VAR_NAME so your key is never stored in plaintext.\nSet the variable in your shell profile (e.g. export ANTHROPIC_API_KEY=sk-...).").
					Value(&apiKey),
				huh.NewInput().
					Title("Model").
					Description("Model name to use for recall questions.").
					Value(&model),
			),
		)
		if err := followUp.Run(); err != nil {
			return fmt.Errorf("%s prompt: %w", selectedProvider, err)
		}
		cfg.AI.APIKey = apiKey
		cfg.AI.Model = model

	case "ollama":
		followUp := huh.NewForm(
			huh.NewGroup(
				huh.NewInput().
					Title("Model").
					Description(`Run "ollama list" to see your installed models.`).
					Value(&model),
			),
		)
		if err := followUp.Run(); err != nil {
			return fmt.Errorf("ollama prompt: %w", err)
		}
		cfg.AI.Model = model
		cfg.AI.APIKey = ""

	case "lm-studio":
		followUp := huh.NewForm(
			huh.NewGroup(
				huh.NewInput().
					Title("Model").
					Description("Enter the model name as shown in LM Studio's model list.").
					Value(&model),
			),
		)
		if err := followUp.Run(); err != nil {
			return fmt.Errorf("lm-studio prompt: %w", err)
		}
		cfg.AI.Model = model
		cfg.AI.APIKey = ""

	case "custom":
		// Custom: full control — base URL, model, and optional API key.
		if baseURL == "" {
			baseURL = "http://localhost:8080/v1"
		}
		followUp := huh.NewForm(
			huh.NewGroup(
				huh.NewInput().
					Title("Base URL").
					Description("Full base URL of your OpenAI-compatible endpoint.\nExample: http://localhost:8080/v1").
					Value(&baseURL),
				huh.NewInput().
					Title("Model").
					Value(&model),
				huh.NewInput().
					Title("API Key (optional)").
					Description("Leave blank if your endpoint does not require authentication.").
					Value(&apiKey),
			),
		)
		if err := followUp.Run(); err != nil {
			return fmt.Errorf("custom provider prompt: %w", err)
		}
		cfg.AI.BaseURL = baseURL
		cfg.AI.Model = model
		cfg.AI.APIKey = apiKey
	}

	return nil
}

func configCmd() *cobra.Command {
	var show bool

	cmd := &cobra.Command{
		Use:   "config",
		Short: "Read and write Total Recall config values",
		RunE: func(cmd *cobra.Command, args []string) error {
			if show {
				return runConfigShow()
			}
			return cmd.Help()
		},
	}

	cmd.Flags().BoolVar(&show, "show", false,
		"Print the fully resolved config with source annotations (user / repo / default)")

	return cmd
}

func runConfigShow() error {
	cfg, err := config.Load(quiet)
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}
	config.Show(cfg, os.Stdout)
	return nil
}

func statusCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "status",
		Short: "Show daemon status and active config",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runStatus()
		},
	}
}

func runStatus() error {
	const healthURL = "http://localhost:7331/health"
	client := &http.Client{Timeout: 1 * time.Second}

	resp, err := client.Get(healthURL)
	if err != nil {
		fmt.Println("✗ Daemon not running on localhost:7331")
		fmt.Println("  Start with: total-recall serve")
		os.Exit(1)
	}
	defer resp.Body.Close()

	var health struct {
		Status string `json:"status"`
	}
	if jsonErr := json.NewDecoder(resp.Body).Decode(&health); jsonErr != nil || health.Status != "ok" {
		fmt.Println("✗ Daemon returned unexpected health response")
		os.Exit(1)
	}

	fmt.Println("✓ Daemon running on localhost:7331")

	cfg, err := config.Load(quiet)
	if err != nil {
		fmt.Fprintf(os.Stderr, "  (could not load config: %v)\n", err)
		return nil
	}
	config.Show(cfg, os.Stdout)
	return nil
}
